version: "3.8"

services:
  elasticsearch:
    image: elasticsearch:8.12.1
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false       # упрощаем тест
      - ELASTIC_PASSWORD=changeme
    ports:
      - "9200:9200"

  api:
    build: .
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - "8000:8000"
    depends_on:
      - elasticsearch
